name: Actions Workflow

# on: [push, pull_request]
on:
  # schedule:
  #   - cron: "0/5 * * * *"
  push:
    branches:
      - master
      - 'feature/*' #this asterick matches any branch starting with feature/ like feature/a or feature/b but doesn't match feature/a/b or feat/c
      - 'feature/**' # matches feature/a/b or feature/a patterns
    # branches-ignore: 
    # tags:
    #   - v1.*
    # paths:
    #   - '**.js' #if we push any any javascript file in our respository
  repository_dispatch:
    types: [build]
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Payload retrieval
        run: echo "${{ github.event.client_payload.env }}"
      - name: List files and Enviornment variables
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_RESPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v1 
      - name: List files after Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Kishan
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"

