name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: node:14.15.0-alpine3.10
    steps:
      - name: Node version
        run: |
          node -v
          cat /etc/os-release