name: Todo

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:15.1.0-alpine3.10
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:14.15.0-alpine3.10
        with:
          entrypoint: '/bin/echo'
          args: "Hello world!"

      - name: Log node version
        uses: docker://node:14.15.0-alpine3.10
        with:
          entrypoint: '/usr/local/bin/node'
          args: "-v"

  golang-docker:
    runs-on: ubuntu-latest
    services:
      react-app:
        image: kishankg123/todoimage:reactimage
        # stdin_open: true
        ports: 
            - "3001:3000"
    
      api-server:
        image: kishankg123/todoimage:golang-image2
        ports:
            - "8081:8080"
        # depends_on:
            # - mongo

      mongo:
        image: mongo
        ports: 
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
    steps:
      - name: Get tasks
        run: curl http://localhost:3001